- name: Ensure install nginx
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - software-properties-common
    - openssh-server
    - nginx
    - supervisor
    - wget

- name: Add virtualhost configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/nginx.conf
  with_items: virtual_hosts
  notify: nginx reload

- name: Add template bob.conf.j2 to default connection
  template: src=bob.conf.j2 dest=/etc/nginx/sites-available/default
  tags: template_nginx

- name: Enable virtualhosts
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  when: item.disabled is not defined
  with_items: virtual_hosts
  notify: nginx reload
