- name: Ensure install nginx
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - software-properties-common
    - openssh-server
    - nginx
    - supervisor
    - wget

- name: Inhabilitar default
  file: path=/etc/nginx/sites-available/default state=absent 
  tags: desdefault

- name: Inhabilitar default sites-enabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  tags: desdefault2

- name: Add template server.conf.j2 to default connection
  template: src=server.conf.j2 dest=/etc/nginx/sites-enabled/bob.conf mode=0600
  tags: template_nginx


- name: Restart service nginx
  shell: service nginx restart