- name: Ensure install mysql
  apt: name={{ item }} state=present # enabled=yes
  with_items:
    #- mysql-server
    - mysql-server-5.6
    - python-pip 
    - python-dev 
    - libmysqlclient-dev
  tags: mysqlInstall

#- name: Install with pip MySQL-python
#  pip: name= {{ item }} state=present
#  with_items:
#    - MySQL-python

- name: Install MySQL-python with pip
  shell: pip install MySQL-python

- name: Copiar archivos de configuración en my.cnf
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf mode=0600
  tags: template_mysql
  notify: restart mysql

- name: Create a new database with name
  mysql_db:
    state: present
    name: bob_{{ item }}
  with_items:
    - ar
    - ar_hp
    - cl
    - cl_hp
    - co
    - co_av
    - co_hp
    - ec
    - mx
    - mx_cp
    - mx_hp
    - pa
    - pe
    - pe_av
    - pe_hp
    - ve
  tags: create_database

- name: Ensure copy database
  copy:
    #src: bob_cl_SD.sql
    src: databases/cl/bob_cl_Data.sql
    dest: /tmp
    mode: 0777
  tags: copy

- name: Import file.sql structure
  mysql_db:
    name: bob_{{ item }}
    login_user: root 
    login_password: ''
    state: import
    target: /vagrant/roles/mysql/files/databases/{{ item }}/bob_{{ item }}_SD.sql
  with_items:
    #- ar
    #- ar_hp
    - cl
    #- cl_hp
    #- co
    #- co_av
    #- co_hp
    - ec
    #- mx
    #- mx_cp
    #- mx_hp
    #- pa
    #- pe
    #- pe_av
    #- pe_hp
    #- ve
  tags: import

- name: Import file.sql with Data
  mysql_db:
    name: bob_{{ item }}
    state: import
    target: /vagrant/roles/mysql/files/databases/{{ item }}/bob_{{ item }}_Data.sql
  with_items:
    #- ar
    #- ar_hp
    - cl
    #- cl_hp
    #- co
    #- co_av
    #- co_hp
    - ec
    #- mx
    #- mx_cp
    #- mx_hp
    #- pa
    #- pe
    #- pe_av
    #- pe_hp
    #- ve
  tags: data