- name: Ensure install mysql
  apt: name={{ item }} state=present # enabled=yes
  with_items:
    - mysql-server
  tags: mysqlInstall


- name: Crear estructura de bases de datos
  shell: mysql -u {{ configuration.mysql.user }} -p {{ configuration.mysql.password }}
  tags: probar conexion